version: "3.9"
services:
  generate_fake_data:
    build: generate/Dockerfile

  postgres:
    build: storage/postgres/Dockerfile
    depends_on:
      - generate_fake_data

  airbyte:
    build: ingestion/airbyte/Dockerfile
    depends_on:
      - postgres

  dagster_dbt:
    build: ./transformation/Dockerfile
    depends_on:
      - airbyte

  metabase:
    build: ./visualization/Dockerfile
    depends_on:
      - dagster_dbt