FROM python:3.8-slim-buster

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /app

# install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        default-libmysqlclient-dev \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

# copy the requirements.txt file into the container
COPY transformation/dagster/requirements.txt ./dagster_requirements.txt
COPY transformation/dbt/requirements.txt ./dbt_requirements.txt

# install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r dagster_requirements.txt
RUN pip install -r dbt_requirements.txt

# copy the contents of the transformation folder into the container
COPY transformation/dagster /app/dagster
COPY transformation/dbt /app/dbt

# run dbt and dagster as a non-root user
RUN adduser --disabled-password --gecos '' dagster
USER dagster

# expose port for dagit
EXPOSE 3000

CMD ["dagit", "-h", "0.0.0.0"]